### ISSUE TITLE
Want to have new feature in this app 🆕

### ISSUE THREAD

**Issue by harsh-100** [devashishsoni98/my-portfolio#1]
- The portfolio looks great ,and css styling is amazing 👍
- A person who wants to look your porfolio as a recruiter will want your resume or CV as pdf or docs , so if this app will have download button which can give him your resume downloaded , it will be really helpful for him 😉

Thanks ❤️

**Comment by devashishsoni98** [comment]
Thank You! and definitely, that is a great suggestion. I will add a download CV button into the website very soon with my CV as a document. 👍😊

**Comment by devashishsoni98** [comment]
Thank you for the suggestion. I have added the Download CV button now. 👍
